"use client";

import React, { useState } from "react";
import Link from "next/link";
import { IconChevronRight, IconPlus, IconArrowRight, IconLock, IconSparkles } from "@tabler/icons-react";

interface InteractiveSkillMapTreeProps {
  hasGoals?: boolean;
  goalTitle?: string;
}

export function InteractiveSkillMapTree({
  hasGoals = false,
  goalTitle = "Calculus Basics",
}: InteractiveSkillMapTreeProps) {
  const [hoveredNode, setHoveredNode] = useState<string | null>(null);

  if (!hasGoals) {
    return (
      <div id="skill-map" className="rounded-lg border border-slate-200/80 bg-white p-6 shadow-sm">
        {/* Header */}
        <div className="flex items-center justify-between mb-2">
          <div>
            <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <span>Your Skill Map</span>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-purple-50 text-[#7C3AED] border border-purple-200">
                Setup Mode
              </span>
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Your personalized skill tree will be generated by AI when you choose a learning quest.
            </p>
          </div>
          <Link
            href="/goals/new"
            className="flex items-center gap-1 text-xs font-bold text-[#6D28D9] hover:underline"
          >
            <span>Create Quest</span>
            <IconChevronRight className="h-3.5 w-3.5" />
          </Link>
        </div>

        {/* Starter Onboarding SVG Skill Tree */}
        <div className="relative w-full overflow-x-auto my-2">
          <svg
            viewBox="0 0 660 170"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className="w-full h-auto min-w-[620px] select-none"
          >
            <defs>
              <linearGradient id="hub-glow" x1="270" y1="50" x2="330" y2="110" gradientUnits="userSpaceOnUse">
                <stop offset="0%" stopColor="#F5F3FF" />
                <stop offset="100%" stopColor="#EDE9FE" />
              </linearGradient>
              <filter id="hub-shadow-start" x="-20%" y="-20%" width="140%" height="140%">
                <feDropShadow dx="0" dy="4" stdDeviation="6" floodColor="#7C3AED" floodOpacity="0.25" />
              </filter>
            </defs>

            {/* Connecting Lines */}
            <line x1="70" y1="80" x2="150" y2="80" stroke="#10B981" strokeWidth="2.5" strokeLinecap="round" />
            <line x1="190" y1="80" x2="274" y2="80" stroke="#8B5CF6" strokeWidth="2.5" strokeLinecap="round" />
            <path d="M 326 80 C 365 80, 395 42, 430 42" stroke="#CBD5E1" strokeWidth="2.5" strokeDasharray="4 4" strokeLinecap="round" fill="none" />
            <path d="M 326 80 C 365 80, 395 118, 430 118" stroke="#CBD5E1" strokeWidth="2.5" strokeLinecap="round" fill="none" />
            <line x1="470" y1="42" x2="570" y2="42" stroke="#E2E8F0" strokeWidth="2.5" strokeLinecap="round" />
            <line x1="470" y1="118" x2="570" y2="118" stroke="#E2E8F0" strokeWidth="2.5" strokeLinecap="round" />

            {/* Node 1: Account Setup (Completed) */}
            <g className="cursor-pointer">
              <circle cx="50" cy="80" r="20" fill="#ECFDF5" stroke="#10B981" strokeWidth="2.5" />
              <path d="M 43 80 L 48 85 L 58 74" stroke="#059669" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" fill="none" />
              <text x="50" y="116" textAnchor="middle" fill="#475569" fontSize="11" fontWeight="600" fontFamily="Inter, sans-serif">
                Account Setup
              </text>
            </g>

            {/* Node 2: Profile (Completed) */}
            <g className="cursor-pointer">
              <circle cx="170" cy="80" r="20" fill="#ECFDF5" stroke="#10B981" strokeWidth="2.5" />
              <path d="M 163 80 L 168 85 L 178 74" stroke="#059669" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" fill="none" />
              <text x="170" y="116" textAnchor="middle" fill="#475569" fontSize="11" fontWeight="600" fontFamily="Inter, sans-serif">
                Profile Ready
              </text>
            </g>

            {/* Node 3: Pick a Quest (Center Active Hub) */}
            <Link href="/goals/new">
              <g className="cursor-pointer" filter="url(#hub-shadow-start)">
                <circle cx="300" cy="80" r="32" fill="#EDE9FE" fillOpacity="0.7" />
                <circle cx="300" cy="80" r="26" fill="url(#hub-glow)" stroke="#7C3AED" strokeWidth="3" />
                <text x="300" y="86" textAnchor="middle" fill="#7C3AED" fontSize="20" fontWeight="700">
                  ✦
                </text>
                <text x="300" y="128" textAnchor="middle" fill="#0F172A" fontSize="12" fontWeight="700" fontFamily="Inter, sans-serif">
                  Pick a Quest
                </text>
              </g>
            </Link>

            {/* Node 4: Target Skills (Locked) */}
            <g className="cursor-pointer opacity-70">
              <circle cx="450" cy="42" r="20" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="2" strokeDasharray="3 3" />
              <path d="M 445 42 L 455 42 M 450 37 L 450 47" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" />
              <text x="450" y="76" textAnchor="middle" fill="#94A3B8" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
                Target Skills
              </text>
            </g>

            {/* Node 5: AI Path (Locked) */}
            <g className="cursor-pointer opacity-70">
              <circle cx="450" cy="118" r="20" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="2" strokeDasharray="3 3" />
              <path d="M 445 118 L 455 118 M 450 113 L 450 123" stroke="#94A3B8" strokeWidth="2" strokeLinecap="round" />
              <text x="450" y="152" textAnchor="middle" fill="#94A3B8" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
                Adaptive Path
              </text>
            </g>

            {/* Node 6: Master Level (Locked) */}
            <g className="cursor-pointer opacity-50">
              <circle cx="590" cy="42" r="18" fill="#F1F5F9" stroke="#E2E8F0" strokeWidth="2" />
              <text x="590" y="76" textAnchor="middle" fill="#94A3B8" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
                Mastery
              </text>
            </g>

            {/* Node 7: Certification (Locked) */}
            <g className="cursor-pointer opacity-50">
              <circle cx="590" cy="118" r="18" fill="#F1F5F9" stroke="#E2E8F0" strokeWidth="2" />
              <text x="590" y="152" textAnchor="middle" fill="#94A3B8" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
                Assessment
              </text>
            </g>
          </svg>
        </div>

        {/* Legend & Action Bar */}
        <div className="flex flex-wrap items-center justify-between border-t border-slate-100 pt-3 text-xs">
          <div className="flex items-center gap-4 text-slate-500 font-medium text-[11px]">
            <span className="flex items-center gap-1.5">
              <span className="h-2.5 w-2.5 rounded-full bg-emerald-500" />
              <span>Completed</span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="h-2.5 w-2.5 rounded-full bg-[#7C3AED]" />
              <span>Current Step</span>
            </span>
            <span className="flex items-center gap-1.5">
              <span className="h-2.5 w-2.5 rounded-full bg-slate-300" />
              <span>Locked</span>
            </span>
          </div>

          <Link
            href="/goals/new"
            className="inline-flex items-center gap-1 font-bold text-[#7C3AED] hover:underline"
          >
            <span>+ Build Your Skill Tree</span>
            <IconArrowRight className="h-3.5 w-3.5" />
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div id="skill-map" className="rounded-lg border border-slate-200/80 bg-white p-6 shadow-sm">
      {/* Header */}
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-base font-bold text-slate-900">Your Skill Map</h3>
        <Link
          href="/dashboard#skill-map"
          className="flex items-center gap-1 text-xs font-bold text-[#6D28D9] hover:underline"
        >
          <span>Explore full map</span>
          <IconChevronRight className="h-3.5 w-3.5" />
        </Link>
      </div>

      {/* 100% Seamlessly Connected SVG Skill Map Graph */}
      <div className="relative w-full overflow-x-auto my-2">
        <svg
          viewBox="0 0 660 170"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          className="w-full h-auto min-w-[620px] select-none"
        >
          <defs>
            <linearGradient id="calc-glow" x1="270" y1="50" x2="330" y2="110" gradientUnits="userSpaceOnUse">
              <stop offset="0%" stopColor="#F5F3FF" />
              <stop offset="100%" stopColor="#EDE9FE" />
            </linearGradient>
            <filter id="hub-shadow" x="-20%" y="-20%" width="140%" height="140%">
              <feDropShadow dx="0" dy="4" stdDeviation="6" floodColor="#7C3AED" floodOpacity="0.25" />
            </filter>
          </defs>

          {/* Connector: Foundations (70,80) -> Algebra (150,80) */}
          <line x1="70" y1="80" x2="150" y2="80" stroke="#10B981" strokeWidth="2.5" strokeLinecap="round" />
          <line x1="190" y1="80" x2="274" y2="80" stroke="#8B5CF6" strokeWidth="2.5" strokeLinecap="round" />
          <path d="M 326 80 C 365 80, 395 42, 430 42" stroke="#8B5CF6" strokeWidth="2.5" strokeDasharray="4 4" strokeLinecap="round" fill="none" />
          <path d="M 326 80 C 365 80, 395 118, 430 118" stroke="#CBD5E1" strokeWidth="2.5" strokeLinecap="round" fill="none" />
          <line x1="470" y1="42" x2="570" y2="42" stroke="#CBD5E1" strokeWidth="2.5" strokeLinecap="round" />
          <line x1="470" y1="118" x2="570" y2="118" stroke="#CBD5E1" strokeWidth="2.5" strokeLinecap="round" />

          {/* Node 1 */}
          <g className="cursor-pointer">
            <circle cx="50" cy="80" r="20" fill="#ECFDF5" stroke="#10B981" strokeWidth="2.5" />
            <path d="M 43 80 L 48 85 L 58 74" stroke="#059669" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" fill="none" />
            <text x="50" y="116" textAnchor="middle" fill="#475569" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
              Foundations
            </text>
          </g>

          {/* Node 2 */}
          <g className="cursor-pointer">
            <circle cx="170" cy="80" r="20" fill="#ECFDF5" stroke="#10B981" strokeWidth="2.5" />
            <path d="M 163 80 L 168 85 L 178 74" stroke="#059669" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" fill="none" />
            <text x="170" y="116" textAnchor="middle" fill="#475569" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
              Core Skills
            </text>
          </g>

          {/* Node 3: Active Goal */}
          <g className="cursor-pointer" filter="url(#hub-shadow)">
            <circle cx="300" cy="80" r="32" fill="#EDE9FE" fillOpacity="0.6" />
            <circle cx="300" cy="80" r="26" fill="url(#calc-glow)" stroke="#7C3AED" strokeWidth="3" />
            <text x="300" y="88" textAnchor="middle" fill="#7C3AED" fontSize="22" fontWeight="700" fontStyle="italic" fontFamily="Georgia, serif">
              ✦
            </text>
            <text x="300" y="128" textAnchor="middle" fill="#0F172A" fontSize="12" fontWeight="800" fontFamily="Inter, sans-serif">
              {goalTitle}
            </text>
          </g>

          {/* Node 4 */}
          <g className="cursor-pointer">
            <circle cx="450" cy="42" r="20" fill="#F5F3FF" stroke="#7C3AED" strokeWidth="2.5" strokeDasharray="3 3" />
            <text x="450" y="48" textAnchor="middle" fill="#7C3AED" fontSize="11" fontWeight="700" fontFamily="Georgia, serif">
              ∂/∂x
            </text>
            <text x="450" y="76" textAnchor="middle" fill="#0F172A" fontSize="11" fontWeight="700" fontFamily="Inter, sans-serif">
              Specialization
            </text>
          </g>

          {/* Node 5 */}
          <g className="cursor-pointer">
            <circle cx="450" cy="118" r="20" fill="#ECFDF5" stroke="#10B981" strokeWidth="2.5" />
            <text x="450" y="152" textAnchor="middle" fill="#0F172A" fontSize="11" fontWeight="700" fontFamily="Inter, sans-serif">
              Applied Practice
            </text>
          </g>

          {/* Node 6 */}
          <g className="cursor-pointer opacity-80">
            <circle cx="590" cy="42" r="20" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="2.5" />
            <text x="590" y="76" textAnchor="middle" fill="#64748B" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
              Advanced Mastery
            </text>
          </g>

          {/* Node 7 */}
          <g className="cursor-pointer opacity-80">
            <circle cx="590" cy="118" r="20" fill="#F8FAFC" stroke="#CBD5E1" strokeWidth="2.5" />
            <text x="590" y="152" textAnchor="middle" fill="#64748B" fontSize="11" fontWeight="500" fontFamily="Inter, sans-serif">
              Projects
            </text>
          </g>
        </svg>
      </div>

      {/* Legend */}
      <div className="flex items-center gap-5 border-t border-slate-100 pt-3 text-xs">
        <span className="flex items-center gap-1.5 font-medium text-slate-600">
          <span className="h-2.5 w-2.5 rounded-full bg-emerald-500" />
          <span>Completed</span>
        </span>
        <span className="flex items-center gap-1.5 font-medium text-slate-600">
          <span className="h-2.5 w-2.5 rounded-full bg-[#7C3AED]" />
          <span>In Progress</span>
        </span>
        <span className="flex items-center gap-1.5 font-medium text-slate-600">
          <span className="h-2.5 w-2.5 rounded-full bg-slate-300" />
          <span>Locked</span>
        </span>
      </div>
    </div>
  );
}
