/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Plan */
        post: operations["create_plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness plus a capability read-out, so a cold deploy is diagnosable.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MilestoneOut */
        MilestoneOut: {
            phase: components["schemas"]["Phase"];
            /** Title */
            title: string;
            /** Total Hours */
            total_hours: number;
            /** Nodes */
            nodes: components["schemas"]["NodeOut"][];
        };
        /**
         * Modality
         * @enum {string}
         */
        Modality: "video" | "lab" | "reading" | "project" | "assessment";
        /** NodeOut */
        NodeOut: {
            /** Skill Id */
            skill_id: string;
            /** Skill Name */
            skill_name: string;
            status: components["schemas"]["NodeStatus"];
            phase: components["schemas"]["Phase"];
            /** Order */
            order: number;
            /** Estimated Hours */
            estimated_hours: number;
            /** Xp */
            xp: number;
            /** Gap Delta */
            gap_delta: number;
            resource: components["schemas"]["ResourceOut"] | null;
            /** Alternatives */
            alternatives?: components["schemas"]["ResourceOut"][];
            /** Rationale */
            rationale: string | null;
            /** Is Remediation */
            is_remediation: boolean;
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "mastered" | "active" | "next" | "locked";
        /**
         * Phase
         * @enum {string}
         */
        Phase: "foundations" | "core" | "advanced" | "capstone";
        /** PlanRequest */
        PlanRequest: {
            /** Goal */
            goal: string;
            /**
             * Hours Per Week
             * @default 10
             */
            hours_per_week: number;
            /** Deadline Weeks */
            deadline_weeks?: number | null;
            /** Budget Usd */
            budget_usd?: number | null;
            /** Preferred Modalities */
            preferred_modalities?: components["schemas"]["Modality"][];
            /** Known */
            known?: {
                [key: string]: number;
            };
            /**
             * Priority
             * @default balanced
             */
            priority: string;
        };
        /** PlanResponse */
        PlanResponse: {
            /** Goal */
            goal: string;
            /** Target Role */
            target_role: string;
            /** Readiness Pct */
            readiness_pct: number;
            /** Total Hours */
            total_hours: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Weeks Required */
            weeks_required: number | null;
            /** Is Feasible */
            is_feasible: boolean;
            /** Prerequisite Violations */
            prerequisite_violations: number;
            /** Milestones */
            milestones: components["schemas"]["MilestoneOut"][];
            /** Gap Count */
            gap_count: number;
        };
        /** ResourceOut */
        ResourceOut: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Duration Display */
            duration_display: string;
            /** Difficulty */
            difficulty: string | null;
            /** Price Usd */
            price_usd: number;
            /** Price Is Estimate */
            price_is_estimate: boolean;
            /** Cost Type */
            cost_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
